spring:
    application:
        name: sa-storage
    data:
        mongodb:
            uri: mongodb://localhost:27017/messages
server:
    port: 8082
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true